language: node_js
node_js:
  - 12
sudo: true

addons:
  chrome: stable


before_script:
  - npm install -g @angular/cli

script:
  - ng build --prod --base-href https://kvaksebastian.github.io/avidi-tech/


before_deploy:
  - echo -e "node_modules\npackage-lock.json" > .gitignore

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local_dir: dist/avidi-tech-task/
  on:
    branch: master
